#!/usr/bin/env python

import sys, cPickle, os, argparse, time
import numpy as np
import matplotlib.pyplot as plt
from ps_analysis.scripts.stager import FileStager
from ps_analysis.scripts.parametrization_fit import pVal_calc
from ps_analysis.hpa.utils import expectation, background_pool, signal_pool_SourceUnivers, signal_trials 

# get arguments
parser = argparse.ArgumentParser()
parser.add_argument("--infile_source_universe", 
                    type=str,
                    required=True,
                    help="Input file with that was generated by source_universe")
parser.add_argument("--infile_signal",
                        type=str,
                        required=True,
                        help="Give indir for signal signal.")
parser.add_argument("--infile_background",
                        type=str,
                        required=True,
                        help="Give indir for background.")
parser.add_argument("--expectation",
                        type=str,
                        required=True,
                        help="Give path to expectation spline")
parser.add_argument("--outdir",
                        type=str,
                        required=True,
                        help="Give outpath.")
parser.add_argument("--n_iter", 
                    type=int,  
                    default=1000,
                    help="Number of iteration to perform for these settings.")
parser.add_argument("--seed", 
                    type=int,  
                    default=None,
                    help="Number of iteration to perform for these settings.")
parser.add_argument("--density", 
                    type=float,  
                    default=None,
                    help="Density of sources.")
args = parser.parse_args()

for k, v in args._get_kwargs():
    print "%15s"%k, v
 
print(33*"-")
                 
RNG = np.random.RandomState(args.seed)
seed_bgd_pool, seed_sig_pool, seed_source_universe = RNG.randint(0, np.iinfo(np.uint32).max, size=3)
                 
# read expectation spline
print("Load expectation ...")
expect = expectation(args.expectation)
    
# get background pool
print("Load background pool ...")
bgd_pool = background_pool()
bgd_pool.load( args.infile_background, seed=seed_bgd_pool)

# get signal pool
print("Load signal pool ...")
sig_pool = signal_pool_SourceUnivers()
sig_pool.load(args.infile_signal, seed=seed_sig_pool)
sig_pool.load_SourceUnivers_representation(args.infile_source_universe, seed_source_universe)  

#### start generating stuff
print("Start generating trials ...")        
out = signal_trials(args.n_iter)
t0 = time.time()
hottest_source = []
n_above = []
while out.need_more_trials():
    bgd            = bgd_pool.get_pseudo_experiment()
    sig, n_tot_inj = sig_pool.get_pseudo_experiment(density=args.density)

    solid_angle_hemisphere = 2*np.pi*(np.sin(np.pi/2) - np.sin(np.radians(-3)))
    solid_angle_per_source = np.pi*np.radians(bgd_pool.min_ang_dist)**2

    data = bgd
    for i, s in enumerate(sig):
        prob = len(data)*solid_angle_per_source/solid_angle_hemisphere
        if RNG.uniform(0, 1) < prob:
            compare_idx = RNG.randint(len(data))
            if data[compare_idx] < s:
                data[compare_idx] = s
        else:
            data = np.concatenate([data, [s]])
            
    # Threshold cut, no pValues below  min_thres
    data = np.sort(data)
    data = data[data >= bgd_pool.cutoff]
    hottest_source.append(np.max(data))
    n_above.append(data >= 6.542) # 5 sigma p-values
    # local pValue calculation and give back maximum significant pValue
    pseudo_result = expect.poisson_test(data)
    
    out.add_trial(n_tot_inj, pseudo_result)
print(time.time()-t0, "sec")
print("... done.")
out.clean_nans()
            
# save stuff
print("Save results")
source_universe_config = ".".join(os.path.basename(args.infile_source_universe).split(".")[:-1])
with FileStager(os.path.join(args.outdir,"HPA_source_universe_signal_trials_{source_universe_config}_density_{args.density}_seed_{args.seed}.npy".format(**locals())), "w") as open_file:
    np.save(open_file, out.trials)
with FileStager(os.path.join(args.outdir,"HPA_source_universe_signal_trials_{source_universe_config}_density_{args.density}_seed_{args.seed}.args".format(**locals())), "w") as open_file:
    cPickle.dump(args, open_file)
with FileStager(os.path.join(args.outdir,"HPA_source_universe_hottest_source_{source_universe_config}_density_{args.density}_seed_{args.seed}.cPickle".format(**locals())), "w") as open_file:
    cPickle.dump(hottest_source, open_file, protocol=2)
with FileStager(os.path.join(args.outdir,"HPA_source_universe_n_above_{source_universe_config}_density_{args.density}_seed_{args.seed}.cPickle".format(**locals())), "w") as open_file:
    cPickle.dump(n_above, open_file, protocol=2)
